##
# Build Spec for AWS CodeBuild
#
# Builds & Pushes Docker images for the Service
---
version: 0.2

phases:
  pre_build:
    commands:
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query 'Account' --output text)
      - echo AWS Account $AWS_ACCOUNT_ID
      - echo Logging into ECR
      - $(aws ecr get-login --no-include-email --region eu-west-1)
      - REPO_URI=$AWS_ACCONT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/eventwrite
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-8)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - docker build -t eventwrite:latest .
      - docker tag eventwrite:latest ${REPO_URI}:${IMAGE_TAG}
      - docker tag eventwrite:latest ${REPO_URI}:latest
  post_build:
    commands:
      - docker push ${REPO_URI}:${IMAGE_TAG}
      - docker push ${REPO_URI}:latest
      - printf '{"ImageURI":"%s","ImageTags":["%s"]}' $REPO_URI:$IMAGE_TAG $IMAGE_TAG > imageDetail.json

artifacts:
  files: imageDetail.json