##
# Build Spec for AWS CodeBuild
#
# Builds & Pushes Docker images for the Service
---
version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region eu-west-1)
      - REPO_URI=$REPOSITORY_URL
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-8)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - docker build -t eventwrite:latest .
      - docker tag eventwrite:latest ${REPO_URI}:${IMAGE_TAG}
      - docker tag eventwrite:latest ${REPO_URI}:latest
  post_build:
    commands:
      - docker push ${REPO_URI}:${IMAGE_TAG}
      - docker push ${REPO_URI}:latest
      - printf '{"ImageURI":"%s","ImageTags":["%s"]}' $REPO_URI:$IMAGE_TAG $IMAGE_TAG > imageDetail.json

artifacts:
  files: imageDetail.json