@host = http://event-appli-1ihr1c66xr1ce-1603930988.eu-west-1.elb.amazonaws.com
#  @host = http://localhost:8080


###
# Send Events
#
POST {{host}}/events
Content-Type: application/json
X-Api-Key: test

{
    "events": [
        {
            "name": "test_event",
            "url": "",
            "timestamp": "{{$datetime iso8601}}",
            "metrics": {
                "some_metric": 0,
                "some_other_metric": 1
            },
            "attributes": {
                "test": "true",
                "some_other_key": "some_other_value",
                "uuid": "{{$guid}}"
            }
        },
        {
            "name": "page_load",
            "url": "http://example.com/",
            "timestamp": "{{$datetime iso8601}}",
            "metrics": {
                "load_time_total_us": 19029
            },
            "attributes": {
                "test": "true",
                "client_addr": "192.168.0.1"
            }
        },
        {
            "name": "page_load",
            "url": "http://example.com/test",
            "timestamp": "{{$datetime iso8601}}",
            "metrics": {
                "load_time_total_us": 129894859
            },
            "attributes": {
                "test": "true",
                "client_addr": "192.168.1.1"
            }
        }
    ]
}


###
# TEST
GET {{host}}/
X-Api-Key: test