AWSTemplateFormatVersion: 2010-09-09
Description: |-
  Development & Deployment Pipeline for Eventwrite


Resources:

  DockerRepo:
    Type: AWS::ECR::Repository
    Properties: {}

  BuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: [ "sts:AssumeRole"]
            Principal:
              Service: [ codebuild.amazonaws.com ]
      Policies:
        - PolicyName: ECRAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Resource: ['*']
                Action:
                  - logs:PutLogEvents
                  - logs:CreateLogStream
                  - logs:CreateLogGroup
              - Effect: Allow
                Resource:  '*'
                Action:
                 - ecr:GetAuthorizationToken
              - Effect: Allow
                Resource:
                  - !GetAtt DockerRepo.Arn
                Action:
                  - ecr:InitiateLayerUpload
                  - ecr:UploadLayerPart
                  - ecr:CompleteLayerUpload
                  - ecr:PutImage
  
  BuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      ServiceRole: !GetAtt BuildRole.Arn
      Artifacts: {Type: NO_ARTIFACTS}
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        PrivilegedMode: yes
        Image: aws/codebuild/standard:2.0-1.12.0
        Type: LINUX_CONTAINER
      Source:
        Type: GITHUB
        Location: https://github.com/LeoAdamek/eventwrite
    
Outputs:
  RepoName:
    Export: 
      Name: eventwrite-ecr-repo-name
    Value: !Ref DockerRepo
