openapi: '3.0.0'


info:
  title: Eventwrite
  version: '0.1.0'

paths:
  /events:
    post:
      summary: Submit events
      description: >
        Submit a set of events to be recorded
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: 'object'
              additionalProperties: false
              properties:
                events:
                  type: array
                  minItems: 1
                  items:
                    $ref: '../schema/event.schema.json'
      responses:
        '202':
          description: Events accepted
          content:
            application/json:
              schema: {} # TODO
